// Generated by CoffeeScript 1.8.0
(function() {
  var isPrime, largestPrimeFactorOf;

  isPrime = function(num) {
    var i, m, _i;
    m = Math.sqrt(num);
    if (num < 2) {
      false;
    }
    for (i = _i = 3; _i <= m; i = _i += 2) {
      if (num % i === 0) {
        return false;
      }
    }
    return true;
  };

  largestPrimeFactorOf = function(num) {
    var i, largestPrime, m, _i;
    m = Math.sqrt(num);
    for (i = _i = 3; _i <= m; i = _i += 2) {
      if (isPrime(i) && num % i === 0) {
        largestPrime = i;
      }
    }
    return largestPrime;
  };

  console.log(largestPrimeFactorOf(600851475143));

}).call(this);
