// Generated by CoffeeScript 1.8.0
(function() {
  var multipesOf3and5, multipesOf3and5sum;

  multipesOf3and5 = function(limit) {
    var arr, multipesArr, number, _i, _j, _len, _results;
    if (limit == null) {
      limit = 10;
    }
    arr = (function() {
      _results = [];
      for (var _i = 1; 1 <= limit ? _i < limit : _i > limit; 1 <= limit ? _i++ : _i--){ _results.push(_i); }
      return _results;
    }).apply(this);
    multipesArr = [];
    for (_j = 0, _len = arr.length; _j < _len; _j++) {
      number = arr[_j];
      if (number % 3 === 0 || number % 5 === 0) {
        multipesArr.push(number);
      }
    }
    return multipesArr;
  };

  multipesOf3and5sum = multipesOf3and5(1000).reduce(function(a, b) {
    return a + b;
  });

  console.log(multipesOf3and5sum);

}).call(this);
