// Generated by CoffeeScript 1.8.0
(function() {
  var evenElementsOf, evenFibs, sequenceTo;

  sequenceTo = function(limit, sequence) {
    var len;
    if (sequence == null) {
      sequence = [0, 1];
    }
    while (true) {
      len = sequence.length;
      sequence.push(sequence[len - 1] + sequence[len - 2]);
      if (sequence[len] > limit) {
        sequence.pop();
        break;
      }
    }
    return sequence;
  };

  evenElementsOf = function(array) {
    var element, evenArr;
    return evenArr = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        element = array[_i];
        if (element % 2 === 0) {
          _results.push(element);
        }
      }
      return _results;
    })();
  };

  evenFibs = evenElementsOf(sequenceTo(4000000));

  console.log(evenFibs.reduce(function(a, b) {
    return a + b;
  }));

}).call(this);
